modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"

[[mods]]
modId="spellstorm"
version="${file.jarVersion}"
displayName="Spell Storm"
logoFile="logo.png"
credits="Credits for my ego!"
authors="DarkLions"
description='''
This mod add new magical items and other stuffs.
'''
[[dependencies.spellstorm]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16]"
    ordering="NONE"
    side="BOTH"
